### ISSUE TITLE
Gewicht - Historie

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#1]
- Möglichkeit momentanes Gewicht zu erfassen
- Möglichkeit alte Einträge in Tabellen oder Graphenform einzusehen
- Exportfunktio

ToDo:
- neuen table in DB anlegen
- neue Activity
- DB funktion zum hinzufüge

**Comment by FAUSheppy** [comment]
https://github.com/beekama/NutritionApp/commit/e49d3a1c43edd735cde3af5ad8b008d87e6fce9f

**Comment by beekama** [comment]
7657e5a354332ed6f83d9aa57f64a70ae2338e88
d8f5ecfe15712d0272551f52047e8437b8671d1f
Done:
- Add to Json-Import/Export
- Update current weight (config) on weightAdd if appropriate and recalculate bmi/calorie requirement

ToDo:
- Design changes

**Comment by FAUSheppy** [comment]
I think this Issue is done, Design changes are a general thing all over the place, also I found a new bug with it.

Followup Issue:
https://github.com/beekama/NutritionApp/issues/17
