### ISSUE TITLE
remove elements without match from food_nutrient_tables

### ISSUE THREAD

**Issue by beekama** [beekama/NutritionApp#12]
In 'make_db.py' unnecessary elements are already removed from the food-table. These elements must now **also be filtered from the food_nutrient-tables**.

**Comment by FAUSheppy** [comment]
Implemented here: https://github.com/beekama/NutritionApp/commit/0538a8f88aa515596953e5789fe501d4af70b707
Fix some windows-lineendings and white-spaces: https://github.com/beekama/NutritionApp/commit/b30c8816826ddf58c3ce99bf0afe0bad8eb32164

**Comment by FAUSheppy** [comment]
New Food-db also uploaded to usual location m.athq.de/food.db (~32mb, 50% down)
