### ISSUE TITLE
Portions-/Mengen Auswahl

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#2]
- In Moment wird nur das Gewicht in gramm gespeichert, irgendwie müssen die ausgewählten Portionen gespeichert werden. -> DB Table erweitern, Datenbankfunktion addExistingFood erweitern
- Die Portionsauswahl sollte anhand der vorgegebenen Datenfelder in den USDA Daten erfolgen, bzw automatisch generiert derweden -> Datenbank funktion
- siehe runSelectionPipeline Funktion(en) für UI Anpassungen
- Detailansicht in Journal anpassen damit dort auch portionen bei der Menge angezeigt und ausgewählt werden können
- Add Custom Food, Serving Size sollte eine Indikation der möglichen Einheiten angeben, z.B. Serving Size "Cup" oder "Gram", in moment rechnet er damit nur die nutrition runter, das muss man nochmal genau anschauen

**Comment by beekama** [comment]
0f7ccbbe52071676c74575d9eac2f0c0b9c32369
9d36e96887777bd945a18bc4bae058807c3fde7f
6911a12615a20e240fe3dd62db5861b9ba22a647
Done:
- Free text input for amount
- Portiontypes according to food_portion-table

ToDo:
- Improve algorithm to enlarge number of portion_types
- Design

**Comment by FAUSheppy** [comment]
> Improve algorithm to enlarge number of portion_types
> Design
Done: https://github.com/beekama/NutritionApp/commit/f321242793cbe59cc02e24aa11d4192448bfa032
