### ISSUE TITLE
Do not solely rely on Locale.getDefault

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#31]
Use the In-App German/English switch to affect localization Settings for everything, not just the Database entries (as is currently the case), instead of relying on the phones defaul locale setting.

**Comment by beekama** [comment]
3221c8c0da51027fb07e991993aeb80d34f2a1fe
d72df32e9635043b3a9d74effefac069d78b5258
846f54334e5c510efa7fa76ce6cf0c960f39b22d
