### ISSUE TITLE
Colloquial Names for Nutrition Elements

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#7]
Nutrition Elements are currently displayed by their Enum name, aka: 

    VITAMIN_A or VITAMIN_B12

There should function to map those to localized colloquial names, e.g for English:

    Vitamin A
    Vitamin B12

Should probably use string resources.

**Comment by beekama** [comment]
https://github.com/beekama/NutritionApp/commit/a5376212cafe9dd7114185ec031c337bcd275d9b
