### ISSUE TITLE
Amount Selection In Food Group Details

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#8]
The amount selection for already selected foods is currently just an Edit-Text with the Unit name behind it (for example "GRAM").

This should be unified in a single field, containing the same information (amount & unit) but being a button which opens the same amount selector the add-food pipeline opens (meaning the selector with unit and suggested amounts).

Here's a reminder on how this looked in the other app:
![Screenshot_20210627-010724](https://user-images.githubusercontent.com/14907292/123527972-22394c00-d6e4-11eb-8ca4-7ae324eb8c0b.png)

**Comment by beekama** [comment]
[9d36e96887777bd945a18bc4bae058807c3fde7f](https://github.com/beekama/NutritionApp/issues/2#issuecomment-1068351696)

**Comment by FAUSheppy** [comment]
Done
